name: Set Repository Topics

on:
  push:
    branches:
      - prod
      - dev

jobs:
  set_topics:
    runs-on: ubuntu-latest
    steps:
      - name: Set topics
        run: |
          curl \
            -X PUT \
            -H "Authorization: token ${{ secrets.GH_TOKEN }}" \
            -H "Accept: application/vnd.github.mercy-preview+json" \
            -d '{"names": ["topic1","topic2","topic3"]}' \
            https://api.github.com/repos/saranagaoka/actiontest/topics
            
