name: Set Repository Topics

on:
  push:
    branches:
      - prod
      - dev

jobs:
  set_topics:
    runs-on: ubuntu-latest
    steps:
      - name: PrintToken
        run: echo "${{ secrets.TOKEN_GH }}"
      - name: Set topics
        run: |
          curl -L \
            -X PUT \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GH_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/saranagaoka/actionstest/topics \
            -d '{"names":["octocat","atom","electron","api", "pies"]}'
            

        
