name: Set Topics

on:
  push:
    branches:
      - prod
      - dev

jobs:
  build:
    name: Set Topics
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set topics
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          curl \
            -X PUT \
            -H "Authorization: token $GH_TOKEN" \
            -H "Accept: application/vnd.github.mercy-preview+json" \
            -d '{"names": ["sara","sara1","sara2"]}' \
            https://api.github.com/repos/saranagaoka/actiontest/topics
