name: Set Topics

on:
  push:
    branches:
      - prod
      - dev

jobs:
  build:
    name: Set Topics
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      
      - name: Install GitHub CLI
        run: |
          curl -sSL https://github.com/cli/cli/releases/download/v2.4.0/gh_2.4.0_linux_amd64.tar.gz | sudo tar xz -C /usr/local/bin --strip-components=2 gh_2.4.0_linux_amd64/bin/gh

      - name: Set topics
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          echo $GH_TOKEN | gh auth login --with-token
          gh api repos/saranagaoka/actiontest/topics -X PUT -F names='["sara","sara1","sara2"]'
